### ISSUE TITLE
1주차 Homework 결과

### ISSUE THREAD

**Issue by CWNU-djc** [gitjaewon/20213086#1]
잘 수행하였습니다. 
시간 엄수 바랍니다.
결과 A

**Comment by gitjaewon** [comment]
교수님 저 3일전에 올렸는데 과제명칭을 바꿔 시간이 바뀌었습니다
![image](https://user-images.githubusercontent.com/100751751/157873964-97db24c1-1314-4fe4-b4a0-46505ca29a35.png)

**Comment by gitjaewon** [comment]
> 잘했다. 시간 엄수. 결과 A

교수님 저 3일전에 올렸는데 과제명칭을 보기편하게 보려고 교수님이 말씀하신 검사시간 이후에 이름을바꿧는데 시간도 같이 바꼇습니다   
![image](https://user-images.githubusercontent.com/100751751/157873964-97db24c1-1314-4fe4-b4a0-46505ca29a35.png)
![image](https://user-images.githubusercontent.com/100751751/157875122-8007cd53-a817-4a4e-8913-2222c77ea38d.png)

**Comment by CWNU-djc** [comment]
보내준 메일 확인했습니다. A -> A+
